### ISSUE TITLE
Option remaining selected

### ISSUE THREAD

**Issue by akbasferhat** [geekhybrid/vue3-tree-vue#29]
Hi,

When I select any option, the other options remain selected.
![image](https://github.com/geekhybrid/vue3-tree-vue/assets/58658353/35fa1e30-d744-46be-8678-4cb58f42fdf3)

Also some values appear as [object Object].
![image](https://github.com/geekhybrid/vue3-tree-vue/assets/58658353/abbca8b7-5782-49c2-9247-2617d9b79a05)

![image](https://github.com/geekhybrid/vue3-tree-vue/assets/58658353/1528b81c-96b2-4ffa-92b8-44f51f28e13e)
![image](https://github.com/geekhybrid/vue3-tree-vue/assets/58658353/64354785-91c6-48b2-90dc-db834ed94b23)

**Comment by geekhybrid** [comment]
Thanks for reporting this. I'll have a look today.

**Comment by geekhybrid** [comment]
I wasn't able to reproduce this.

Can you update this project file with your code sample so we figure out why ?
https://playcode.io/1799958

Also note I tested with the latest version. But feel free to update the package.json to your version and we can go from there.

**Comment by akbasferhat** [comment]
Hello, also i am using latest verision, here is my code sample

https://playcode.io/1800213

**Comment by geekhybrid** [comment]
> Hello, also i am using latest verision, here is my code sample
> 
> https://playcode.io/1800213

Quickly had a look. The issue is your `id` field is not unique for each node.
In way older versions you had to explicitly specify one. Now, you don't. If an `id` field exist we will use that else we generate a unique one. I removed all `id` fields and it worked as expected.

I'll leave this open for a day if you have any further feedback on the same issue, after which I will close.

**Comment by akbasferhat** [comment]
Thank you, it's my misunderstanding 👍
